name: Deploy ClickOnce to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and Publish ClickOnce
      run: |
        dotnet publish -c Release -p:PublishProfile=ClickOnceProfile -p:PublishUrl="https://publize001.github.io/asdw/" -p:ApplicationVersion="1.0.0.${{ github.run_number }}" -o ./dist
        
    - name: Copy published files to root
      run: |
        Copy-Item -Path "./published/*" -Destination "./dist/" -Recurse -Force
      shell: powershell
      
    - name: Create index.html
      run: |
        @"
        <!DOCTYPE html>
        <html>
        <head>
            <title>My Application</title>
            <style>
                body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
                .download-btn { background: #4CAF50; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-size: 18px; }
                .download-btn:hover { background: #45a049; }
            </style>
        </head>
        <body>
            <h1>Download My Application</h1>
            <p>Click the button below to download and install:</p>
            <a href="setup.exe" class="download-btn">Install Application</a>
            <p><small>ClickOnce will handle automatic updates</small></p>
        </body>
        </html>
        "@ | Out-File -FilePath "./dist/index.html" -Encoding UTF8
      shell: powershell
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
